name: Deploy Application

on:
  workflow_run:
    workflows: [Test Application]
    types: [completed]

jobs:
  deploy:
    needs: [Test Application] 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
    
    - name: Gradlew compilacion
      run: |
        chmod ugo+x gradlew
        ./gradlew build

    - name: CodeDeploy despliegue
      run: |
        aws deploy create-deployment --application-name 'Backends' --deployment-group-name 'Backends' --github-location repository='${{github.GITHUB_REPOSITORY}}',commitId='${{github.GITHUB_SHA}}'      